baseURL = "https://avator-one.github.io"
languageCode = "zh-CN"
title = "ZD Blo"
theme = "LeaveIt"
hasCJKLanguage = true
preserveTaxonomyNames = true
paginate = 10
paginatePath = "page"
enableEmoji = false
publishDir = "docs"

# 创建robots.txt，建议设置为true
enableRobotsTXT = true
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
[menu]
  [[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 1
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
  